package Adventure.Type;

public enum CommandType {
    END, INVENTORY, NORD, SOUTH, EAST, WEST, OPEN, CLOSE, DROP, PUT, PUSH, ATTACK, CUT, EQUIP, UNEQUIP, PICK_UP, TALK_TO, GIVE, USE, LOOK, EXAMINE, TURN_OFF, SAVE, LOAD, RELOAD
}
